web:
  build: .
  command: /run.sh
  links:
   - influxdb
  ports:
   - "80:80"

influxdb:
  image: tutum/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  environment:
    - PRE_CREATE_DB=nest

grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  links:
    - influxdb