web:
  build: .
  links:
   - influxdb
  environment:
    - NEST_USERNAME=
    - NEST_PASSWORD=
    - OPENWEATHERMAP_CITYID= #http://openweathermap.org/city - take id from url after search
    - OPENWEATHERMAP_APPID=

influxdb:
  image: tutum/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  environment:
    - PRE_CREATE_DB=nest

grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
